### PR TITLE
First review cycle

### PR DESCRIPTION
**Pull request by boul**
Described cloudstack specific configuration options for nodes, and some minor adjustments

### CODE REVIEW

**Comment by boul** [comment]
@uric added the cloudstack specific stuff, apart from that starting to look pretty neat. Do want to include some samples of node configuration. e.g sample of a vm node, network node and such?

**Comment by uric** [comment]
@boul samples would definitely be useful. Or we can just point to nodecellar and have people look there (a little more hassle to the reader but will be easier to maintain that way)

**Comment by boul** [comment]
pointing to node cellar seems wiser indeed given maintainability

**Comment by uric** [comment]
merged manually, thanks

**Pull request closed without merging**
